---
Metadata:
  AWSToolsMetrics:
    IaC_Generator: "arn:aws:cloudformation:XXX"
Parameters:
  LambdaFunctionStarttaxitripsCodeZipFile7N38H:
    NoEcho: "true"
    Type: "String"
    Description: "(Node.js and Python) The source code of your Lambda function. If\
      \ you include your function source inline with this parameter, CFN places it\
      \ in a file named ``index`` and zips it to create a [deployment package](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-package.html).\
      \ This zip file cannot exceed 4MB. For the ``Handler`` property, the first part\
      \ of the handler identifier must be ``index``. For example, ``index.handler``.\n\
      \  When you specify source code inline for a Node.js function, the ``index``\
      \ file that CFN creates uses the extension ``.js``. This means that LAM treats\
      \ the file as a CommonJS module. ES modules aren't supported for inline functions.\n\
      \   For JSON, you must escape quotes and special characters such as newline\
      \ (``\\n``) with a backslash.\n If you specify a function that interacts with\
      \ an AWS CloudFormation custom resource, you don't have to write your own functions\
      \ to send responses to the custom resource that invoked the function. AWS CloudFormation\
      \ provides a response module ([cfn-response](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html))\
      \ that simplifies sending responses. See [Using Lambda with CloudFormation](https://docs.aws.amazon.com/lambda/latest/dg/services-cloudformation.html)\
      \ for details."
  LambdaFunctionEndtaxitripsCodeS3Key6TwUR:
    NoEcho: "true"
    Type: "String"
    Description: "The Amazon S3 key of the deployment package."
  LambdaFunctionEndtaxitripsCodeImageUriGcLzo:
    NoEcho: "true"
    Type: "String"
    Description: "URI of a [container image](https://docs.aws.amazon.com/lambda/latest/dg/lambda-images.html)\
      \ in the Amazon ECR registry."
  LambdaFunctionStarttaxitripsCodeS3BucketH4vhT:
    NoEcho: "true"
    Type: "String"
    Description: "An Amazon S3 bucket in the same AWS-Region as your function. The\
      \ bucket can be in a different AWS-account."
  LambdaFunctionStarttaxitripsCodeSourceKMSKeyArnSsc0S:
    NoEcho: "true"
    Type: "String"
    Description: "The ARN of the KMSlong (KMS) customer managed key that's used to\
      \ encrypt your function's .zip deployment package. If you don't provide a customer\
      \ managed key, Lambda uses an [owned key](https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#aws-owned-cmk)."
  LambdaFunctionEndtaxitripsCodeSourceKMSKeyArnnZIMT:
    NoEcho: "true"
    Type: "String"
    Description: "The ARN of the KMSlong (KMS) customer managed key that's used to\
      \ encrypt your function's .zip deployment package. If you don't provide a customer\
      \ managed key, Lambda uses an [owned key](https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#aws-owned-cmk)."
  LambdaFunctionStarttaxitripsCodeS3KeyqtBIi:
    NoEcho: "true"
    Type: "String"
    Description: "The Amazon S3 key of the deployment package."
  LambdaFunctionStarttaxitripsCodeImageUriF9vnD:
    NoEcho: "true"
    Type: "String"
    Description: "URI of a [container image](https://docs.aws.amazon.com/lambda/latest/dg/lambda-images.html)\
      \ in the Amazon ECR registry."
  LambdaFunctionEndtaxitripsCodeS3ObjectVersion1GqMm:
    NoEcho: "true"
    Type: "String"
    Description: "For versioned objects, the version of the deployment package object\
      \ to use."
  LambdaFunctionStarttaxitripsCodeS3ObjectVersionbnhSt:
    NoEcho: "true"
    Type: "String"
    Description: "For versioned objects, the version of the deployment package object\
      \ to use."
  LambdaFunctionEndtaxitripsCodeS3BucketOzRpA:
    NoEcho: "true"
    Type: "String"
    Description: "An Amazon S3 bucket in the same AWS-Region as your function. The\
      \ bucket can be in a different AWS-account."
  LambdaFunctionEndtaxitripsCodeZipFileyBU8v:
    NoEcho: "true"
    Type: "String"
    Description: "(Node.js and Python) The source code of your Lambda function. If\
      \ you include your function source inline with this parameter, CFN places it\
      \ in a file named ``index`` and zips it to create a [deployment package](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-package.html).\
      \ This zip file cannot exceed 4MB. For the ``Handler`` property, the first part\
      \ of the handler identifier must be ``index``. For example, ``index.handler``.\n\
      \  When you specify source code inline for a Node.js function, the ``index``\
      \ file that CFN creates uses the extension ``.js``. This means that LAM treats\
      \ the file as a CommonJS module. ES modules aren't supported for inline functions.\n\
      \   For JSON, you must escape quotes and special characters such as newline\
      \ (``\\n``) with a backslash.\n If you specify a function that interacts with\
      \ an AWS CloudFormation custom resource, you don't have to write your own functions\
      \ to send responses to the custom resource that invoked the function. AWS CloudFormation\
      \ provides a response module ([cfn-response](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html))\
      \ that simplifies sending responses. See [Using Lambda with CloudFormation](https://docs.aws.amazon.com/lambda/latest/dg/services-cloudformation.html)\
      \ for details."
Resources:
  S3BucketKinesisdatastreamlabs:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Retain"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: "kinesis-data-stream-labs"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
      Tags:
      - Value: "project"
        Key: "taxiTrip"
  KinesisStreamStarttripstream:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Kinesis::Stream"
    DeletionPolicy: "Retain"
    Properties:
      StreamModeDetails:
        StreamMode: "ON_DEMAND"
      MaxRecordSizeInKiB: 1024
      RetentionPeriodHours: 24
      DesiredShardLevelMetrics: []
      Tags:
      - Value: "startTripStream"
        Key: "taxiTrip"
      Name: "start-trip-stream"
      ShardCount: 4
  LambdaEventSourceMappingOT:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Lambda::EventSourceMapping"
    DeletionPolicy: "Retain"
    Properties:
      StartingPosition: "LATEST"
      BatchSize: 5
      MaximumRetryAttempts: -1
      ParallelizationFactor: 1
      Enabled: true
      EventSourceArn:
        Fn::GetAtt:
        - "KinesisStreamEndtripstream"
        - "Arn"
      MetricsConfig:
        Metrics: []
      FunctionName:
        Fn::GetAtt:
        - "LambdaFunctionEndtaxitrips"
        - "Arn"
      TumblingWindowInSeconds: 0
      BisectBatchOnFunctionError: false
      DestinationConfig:
        OnFailure:
          Destination: "arn:XXX"
      MaximumRecordAgeInSeconds: -1
      Tags:
      - Value: "triggerEndTaxiTrips"
        Key: "taxiTrip"
      MaximumBatchingWindowInSeconds: 0
  IAMRoleCustomlambdarole:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/service-role/AmazonSNSRole"
      - "arn:aws:iam::aws:policy/CloudWatchEventsFullAccess"
      - "arn:aws:iam::aws:policy/AmazonSQSFullAccess"
      - "arn:aws:iam::aws:policy/AmazonSNSFullAccess"
      - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
      - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      - "arn:aws:iam::aws:policy/AmazonKinesisFullAccess"
      - "arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess"
      MaxSessionDuration: 3600
      RoleName: "custom-lambda-role"
      Description: "Allows Lambda functions to call AWS services on your behalf."
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "lambda.amazonaws.com"
      Tags:
      - Value: "project"
        Key: "taxiTrip"
  KinesisStreamEndtripstream:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Kinesis::Stream"
    DeletionPolicy: "Retain"
    Properties:
      StreamModeDetails:
        StreamMode: "ON_DEMAND"
      MaxRecordSizeInKiB: 1024
      RetentionPeriodHours: 24
      DesiredShardLevelMetrics: []
      Tags:
      - Value: "endTripStream"
        Key: "taxiTrip"
      Name: "end-trip-stream"
      ShardCount: 4
  LambdaEventSourceMapping:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Lambda::EventSourceMapping"
    DeletionPolicy: "Retain"
    Properties:
      StartingPosition: "LATEST"
      BatchSize: 5
      MaximumRetryAttempts: -1
      ParallelizationFactor: 1
      Enabled: true
      EventSourceArn:
        Fn::GetAtt:
        - "KinesisStreamStarttripstream"
        - "Arn"
      MetricsConfig:
        Metrics: []
      FunctionName:
        Fn::GetAtt:
        - "LambdaFunctionStarttaxitrips"
        - "Arn"
      TumblingWindowInSeconds: 0
      BisectBatchOnFunctionError: false
      DestinationConfig:
        OnFailure:
          Destination: "arn:XXX"
      MaximumRecordAgeInSeconds: -1
      Tags:
      - Value: "triggerStartTaxiTrips"
        Key: "taxiTrip"
      MaximumBatchingWindowInSeconds: 0
  LambdaFunctionEndtaxitrips:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Lambda::Function"
    DeletionPolicy: "Retain"
    Properties:
      MemorySize: 128
      Description: ""
      TracingConfig:
        Mode: "PassThrough"
      Timeout: 300
      RuntimeManagementConfig:
        UpdateRuntimeOn: "Auto"
      Handler: "lambda_function.lambda_handler"
      Code:
        SourceKMSKeyArn:
          Ref: "LambdaFunctionEndtaxitripsCodeSourceKMSKeyArnnZIMT"
        S3ObjectVersion:
          Ref: "LambdaFunctionEndtaxitripsCodeS3ObjectVersion1GqMm"
        S3Bucket:
          Ref: "LambdaFunctionEndtaxitripsCodeS3BucketOzRpA"
        ZipFile:
          Ref: "LambdaFunctionEndtaxitripsCodeZipFileyBU8v"
        ImageUri:
          Ref: "LambdaFunctionEndtaxitripsCodeImageUriGcLzo"
        S3Key:
          Ref: "LambdaFunctionEndtaxitripsCodeS3Key6TwUR"
      Role:
        Fn::GetAtt:
        - "IAMRoleCustomlambdarole"
        - "Arn"
      FileSystemConfigs: []
      FunctionName: "end-taxi-trips"
      Runtime: "python3.10"
      PackageType: "Zip"
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: "/aws/lambda/end-taxi-trips"
      RecursiveLoop: "Terminate"
      Environment:
        Variables:
          GLUE_JOB_NAME: "process-failed-trips"
          DDB_TABLE_NAME: "taxi_trip_details"
          SQS_URL: "https://sqs.us-east-1.amazonaws.com/596220994208/failed-updated-trips"
      EphemeralStorage:
        Size: 512
      Tags:
      - Value: "endTaxiTrips"
        Key: "taxiTrip"
      Architectures:
      - "x86_64"
  DynamoDBTableTaxitripdetails:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: "Retain"
    Properties:
      SSESpecification:
        SSEEnabled: false
      TableName: "taxi_trip_details"
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "trip_id"
      ContributorInsightsSpecification:
        Enabled: false
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      WarmThroughput:
        ReadUnitsPerSecond: 12000
        WriteUnitsPerSecond: 4000
      KeySchema:
      - KeyType: "HASH"
        AttributeName: "trip_id"
      DeletionProtectionEnabled: false
      TableClass: "STANDARD"
      Tags:
      - Value: "taxiTripDetails"
        Key: "taxiTrip"
      TimeToLiveSpecification:
        Enabled: false
  SQSQueueFailedupdatedtrips:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::SQS::Queue"
    DeletionPolicy: "Retain"
    Properties:
      SqsManagedSseEnabled: true
      ReceiveMessageWaitTimeSeconds: 0
      DelaySeconds: 0
      MessageRetentionPeriod: 259200
      MaximumMessageSize: 1048576
      VisibilityTimeout: 30
      QueueName: "failed-updated-trips"
      Tags:
      - Value: "failedUpdatedTrips"
        Key: "taxiTrip"
  SNSTopicInvalidtaxitrips:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::SNS::Topic"
    DeletionPolicy: "Retain"
    Properties:
      TracingConfig: "PassThrough"
      DisplayName: "Notifications to streaming taxi trips"
      FifoTopic: false
      Subscription:
      - Endpoint: "whudylnbp@gmail.com"
        Protocol: "email"
      Tags:
      - Value: "invalidTaxiTrips"
        Key: "taxiTrip"
      ArchivePolicy: {}
      TopicName: "Invalid-taxi-trips"
  LambdaFunctionStarttaxitrips:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Lambda::Function"
    DeletionPolicy: "Retain"
    Properties:
      MemorySize: 128
      Description: ""
      TracingConfig:
        Mode: "PassThrough"
      Timeout: 300
      RuntimeManagementConfig:
        UpdateRuntimeOn: "Auto"
      Handler: "lambda_function.lambda_handler"
      Code:
        SourceKMSKeyArn:
          Ref: "LambdaFunctionStarttaxitripsCodeSourceKMSKeyArnSsc0S"
        S3ObjectVersion:
          Ref: "LambdaFunctionStarttaxitripsCodeS3ObjectVersionbnhSt"
        S3Bucket:
          Ref: "LambdaFunctionStarttaxitripsCodeS3BucketH4vhT"
        ZipFile:
          Ref: "LambdaFunctionStarttaxitripsCodeZipFile7N38H"
        ImageUri:
          Ref: "LambdaFunctionStarttaxitripsCodeImageUriF9vnD"
        S3Key:
          Ref: "LambdaFunctionStarttaxitripsCodeS3KeyqtBIi"
      Role:
        Fn::GetAtt:
        - "IAMRoleCustomlambdarole"
        - "Arn"
      FileSystemConfigs: []
      FunctionName: "start-taxi-trips"
      Runtime: "python3.10"
      PackageType: "Zip"
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: "/aws/lambda/start-taxi-trips"
      RecursiveLoop: "Terminate"
      Environment:
        Variables:
          DDB_TABLE_NAME: "taxi_trip_details"
          SNS_TOPIC_ARN: "arn:XXX:Invalid-taxi-trips"
      EphemeralStorage:
        Size: 512
      Tags:
      - Value: "startTaxiTrips"
        Key: "taxiTrip"
      Architectures:
      - "x86_64"
